// Code generated by goctl. DO NOT EDIT!
// Source: book.proto

package bookclient

import (
	"context"

	"book/service/book/rpc/book"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindByNameReq  = book.FindByNameReq
	FindByNameResp = book.FindByNameResp

	Book interface {
		FindByName(ctx context.Context, in *FindByNameReq, opts ...grpc.CallOption) (*FindByNameResp, error)
	}

	defaultBook struct {
		cli zrpc.Client
	}
)

func NewBook(cli zrpc.Client) Book {
	return &defaultBook{
		cli: cli,
	}
}

func (m *defaultBook) FindByName(ctx context.Context, in *FindByNameReq, opts ...grpc.CallOption) (*FindByNameResp, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindByName(ctx, in, opts...)
}
