// Code generated by goctl. DO NOT EDIT.
package types

type SearchReq struct {
	Name string `form:"name"`
}

type SearchResp struct {
	Name  string `json:"name"`
	Type  string `json:"type"`
	Count int    `json:"count"`
}
