// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"book/service/book/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Logger},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/book/add",
					Handler: addHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/book/remove/:id",
					Handler: removeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/book/mod",
					Handler: modHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/book/findByName",
					Handler: findByNameHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/book/ping",
				Handler: pingHandler(serverCtx),
			},
		},
	)
}
